#:schema https://raw.githubusercontent.com/air-verse/air/0a3f56961f682c08c2d012dbf828188b4e12e854/air.schema.json
#air --build.cmd "go build -o ./tmp/main ./cmd/web" --build.entrypoint "./tmp/main"
root = "."
tmp_dir = "tmp"

[build]
  bin="./tmp/main"
  entrypoint="./tmp/main"
  # args_bin = ["-addr=':9999' -help"]
  cmd = "go build -o ./tmp/main ./cmd/web"
  exclude_dir = ["tmp", "ui", "client"]
  include_ext = ["go"]
[color]
  app = "blue"
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"